In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
import matplotlib.collections as mc
from matplotlib import transforms
import numpy as np
from sklearn.cluster import AgglomerativeClustering
import scipy.cluster.hierarchy as sch
import fastcluster as fcl
from scipy.spatial.distance import pdist, squareform
from matplotlib.collections import PatchCollection
from matplotlib.patches import Rectangle, Circle, RegularPolygon, Polygon
import matplotlib as mpl
from decimal import Decimal
import seaborn as sns
from PIL import Image


In [2]:
from omniplot import plot as  op

In [3]:
op.__file__

'/home/koh/anaconda3/envs/omniplot310t/lib/python3.10/site-packages/omniplot/plot.py'

In [4]:
%matplotlib tk

In [5]:
im=Image.open("/home/koh/Pictures/wave512.jpg")

In [6]:
plt.imshow(np.array(im)[:,:,0])

In [7]:
op.heatmap(pd.DataFrame(np.array(im)[:,:,1][::-1]),row_cluster=False, col_cluster=False)

Assuming data is a wide form
figsize:  [14.586894586894587, 10.0]


{'row_clsuter': {},
 'col_cluster': {},
 'axes': {'heatmap': <Axes: >, 'colorbar': <Axes: xlabel='z-score'>},
 'colsort': array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
   

/home/koh/anaconda3/envs/omniplot310t/lib/python3.10/tkinter/__init__.py:839: UserWarning: There are no gridspecs with layoutgrids. Possibly did not call parent GridSpec with the "figure" keyword
  func(*args)


In [8]:
df=sns.load_dataset("penguins")

In [9]:
_df=df[["species","island", "sex"]]

In [10]:
_df.values

array([['Adelie', 'Torgersen', 'Male'],
       ['Adelie', 'Torgersen', 'Female'],
       ['Adelie', 'Torgersen', 'Female'],
       ...,
       ['Gentoo', 'Biscoe', 'Male'],
       ['Gentoo', 'Biscoe', 'Female'],
       ['Gentoo', 'Biscoe', 'Male']], dtype=object)

In [11]:
_df=_df.fillna("NA")

In [12]:
import numpy as np
from kmodes.kmodes import KModes

km = KModes(n_clusters=3, init='Huang', n_init=5, verbose=1)


clusters = km.fit_predict(_df.values)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 28, cost: 265.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 34, cost: 253.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 80, cost: 236.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 0, cost: 267.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 129, cost: 226.0
Run 5, iteration: 2/100, moves: 22, cost: 226.0
Best run was number 5


In [13]:
val=df[["bill_length_mm","bill_depth_mm","flipper_length_mm"]].dropna(0)

/tmp/ipykernel_8463/201308460.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  val=df[["bill_length_mm","bill_depth_mm","flipper_length_mm"]].dropna(0)


In [14]:
X=val.values

In [15]:
X=(X-np.mean(X,axis=0)[None,:])/np.std(X,axis=0)[None,:]

In [16]:
from sklearn.cluster import KMeans

In [17]:
kmeans=KMeans(n_clusters=3, random_state=0, n_init="auto").fit(X)

In [18]:
X.mean(axis=0)

array([ 1.66208827e-16, -1.41277503e-15, -8.31044135e-16])

In [19]:
kmeans.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [20]:
dfX=pd.DataFrame(X, columns=["bill_length_mm","bill_depth_mm","flipper_length_mm"])

In [21]:
dfX["kmeans"]=kmeans.labels_
dfX["mean"]=X.mean(axis=1)

In [22]:
dfX=dfX.sort_values(['kmeans', 'mean'], ascending=[True, True])

In [23]:
dfX.index

Int64Index([207, 157, 212, 163, 165, 192, 189, 213, 203, 194,
            ...
            130,  84, 136,  52,  34,  94,  48, 100,  60,  16],
           dtype='int64', length=342)

In [24]:
srtindex=np.lexsort((X.mean(axis=1),kmeans.labels_))

In [25]:
srtindex

array([207, 157, 212, 163, 165, 192, 189, 213, 203, 194, 179, 154, 151,
       201, 161, 172, 186, 156, 169, 175, 215, 197, 187, 159, 200,  72,
       210,  42, 216, 170, 128, 199, 110, 195, 185, 168, 158, 218, 177,
       174, 153, 178, 193, 196, 152, 164, 209, 206,  18, 176, 184, 202,
       167, 166, 208, 162, 160, 155, 204, 191, 217, 198, 211, 180, 190,
       182, 188, 214, 235, 259, 227, 229, 257, 243, 327, 275, 255, 250,
       325, 277, 279, 267, 219, 261, 224, 303, 265, 251, 264, 271, 231,
       297, 317, 281, 269, 237, 225, 233, 305, 311, 245, 295, 337, 287,
       331, 313, 340, 307, 240, 285, 221, 247, 241, 323, 333, 338, 301,
       283, 273, 328, 223, 244, 232, 299, 292, 293, 335, 268, 276, 246,
       228, 258, 270, 274, 289, 280, 242, 316, 321, 309, 226, 239, 324,
       262, 319, 306, 290, 253, 249, 329, 238, 222, 315, 234, 236, 341,
       298, 291, 256, 230, 248, 288, 254, 272, 322, 278, 336, 339, 263,
       302, 312, 260, 300, 296, 266, 314, 326, 294, 330, 286, 31

In [26]:
# m=np.mean(X, axis=1)
# print(X.shape,m.shape)
# msort=np.argsort(m)

# X=X[msort]
# _labels=kmeans.labels_[msort]

# lsort=np.argsort(_labels)
# X=X[lsort]
# _labels=_labels[lsort]

In [27]:
arr_1 = np.array(["apple", "ball", "cat", "dog"])
arr_1.dtype

dtype('<U5')

In [28]:
type(arr_1[0])==np.str_

True

In [29]:
a=[3,3,3,3,5,5,5,5,5,5,2,2,2]
u, i, c=np.unique(a, return_counts=True, return_index=True
         )
u[np.argsort(i)]

array([3, 5, 2])

In [30]:
d={"a":0}
d.update({"b":1})

In [31]:
d

{'a': 0, 'b': 1}

In [32]:
X.mean(axis=1)

array([-0.50579872, -0.58239602, -0.218398  , -0.26624278,  0.04126657,
       -0.67016479, -0.01519041, -0.62806727,  0.13873929, -0.73705352,
       -0.84568382, -0.54571612,  0.12363023,  0.02832773, -0.71583734,
       -0.14718731,  0.42001039, -0.77266946,  0.69802881, -0.81908103,
       -0.61514033, -0.4270213 , -0.56729425, -0.80144379, -0.56189974,
       -0.38350707, -0.4129914 , -0.80973372, -0.41012837, -0.89064307,
       -0.79461676, -0.46729995, -0.29071165, -0.62590165,  0.2621114 ,
       -0.09073034, -0.37379982, -0.49609016, -0.32416197, -0.75936277,
       -0.12020937, -0.61045512,  0.32505994, -0.8435169 , -0.24466464,
       -0.3090582 , -0.61730065, -0.6169209 ,  0.34986367, -0.52556919,
       -0.24466794, -0.67806507,  0.25780795, -0.74604817, -0.14467364,
       -0.59606397, -0.11230118, -1.01976044, -0.22128153, -0.92300432,
        0.36677441, -0.78992626, -0.20689368, -0.87013489, -0.21012986,
       -0.8161645 , -0.14971549, -0.84278909,  0.18119546, -0.58

In [33]:
np.array([0.9, 'str', 1])

array(['0.9', 'str', '1'], dtype='<U32')

In [34]:
plt.subplots()
sns.heatmap(X)

<Axes: >

In [241]:
#sizes=np.array([mat[i,j] for i in range(mat.shape[0]) for j in range(mat.shape[1])])


In [242]:
mat=np.concatenate([0.5*np.random.uniform(0,1,size=[50, 25]),np.random.uniform(0,1,size=[25, 25])])

In [243]:
from scipy.stats import zscore

In [244]:
mat=zscore(mat, axis=0)

In [245]:
labels=["sample"+str(i) for i in range(75)]

In [246]:
xori=0.1
yori=0.1
ltreew=0.15
ltreeh=0.75
ttreew=0.6
ttreeh=0.1
hmapw=ttreew
hmaph=ltreeh
_tcmap=plt.get_cmap("tab20c")
tcmap = _tcmap(np.linspace(0, 1, 5))
sch.set_link_color_palette([mpl.colors.rgb2hex(rgb[:3]) for rgb in tcmap])
fig=plt.figure(figsize=[8*mat.shape[1]/mat.shape[0],8,])
ax0=fig.add_axes([xori,yori,ltreew,ltreeh])
D=squareform(pdist(mat,metric="euclidean"))
Y = sch.linkage(D, method="ward")

Z = sch.dendrogram(Y,ax=ax0,orientation="left",labels=labels,
                   above_threshold_color='black')
ax0.axis('off')

_tcmap=plt.get_cmap("tab20b")
tcmap = _tcmap(np.linspace(0, 1, 5))
sch.set_link_color_palette([mpl.colors.rgb2hex(rgb[:3]) for rgb in tcmap])
ax1=fig.add_axes([xori+ltreew,yori+ltreeh,ttreew,ttreeh])

Dt=squareform(pdist(mat.T,metric="euclidean"))
Yt = sch.linkage(Dt, method="ward")

Zt = sch.dendrogram(Yt,ax=ax1,orientation="top",above_threshold_color='black')
ax1.axis('off')

mat=mat[Z['leaves']]
mat=mat[:,Zt['leaves']]
row_col=[ [j,i] for i in range(mat.shape[0]) for j in range(mat.shape[1])]
sizes=mat.flatten()
cmap=plt.get_cmap("hot")
# facecolors=np.array([cmap(i) for i in mat.flatten()])
_mat=mat.flatten()
_mat=(_mat-np.min(_mat))/(np.max(_mat)-np.min(_mat))
facecolors=cmap(_mat)
rect = [Rectangle((x - 0.5, y - 0.5), 1, 1)
                  for x, y in row_col]
# circle=[Circle((x, y), 0.5) for x, y in row_col]
    # Create patch collection with specified colour/alpha
pc = PatchCollection(rect, facecolor=facecolors, alpha=1,
                     edgecolor=None)
ax=fig.add_axes([xori+ltreew,yori,hmapw,hmaph])
ax.add_collection(pc)
ax.margins(0.00)
_=ax.set_yticks(np.arange(mat.shape[0]))
_=ax.set_xticks(np.arange(mat.shape[1]))
ax.yaxis.tick_right()
axc=fig.add_axes([0.87,0.065,0.1,0.01])
norm = mpl.colors.Normalize(vmin=np.amin(mat), vmax=np.amax(mat))

cb1 = mpl.colorbar.ColorbarBase(axc, cmap=cmap,
                                norm=norm,
                                orientation='horizontal')
cb1.set_label('Some Units')

<ipython-input-246-e1ce0e46d333>:15: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  Y = sch.linkage(D, method="ward")
<ipython-input-246-e1ce0e46d333>:27: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  Yt = sch.linkage(Dt, method="ward")


In [247]:
aa, b,c=zip(*sorted(zip(Z["icoord"], Z["dcoord"], Z["color_list"])))

In [248]:
aa

([5.0, 5.0, 15.0, 15.0],
 [10.0, 10.0, 40.0, 40.0],
 [25.0, 25.0, 35.0, 35.0],
 [25.0, 25.0, 109.6875, 109.6875],
 [30.0, 30.0, 50.0, 50.0],
 [45.0, 45.0, 55.0, 55.0],
 [65.0, 65.0, 75.0, 75.0],
 [67.34375, 67.34375, 282.6953125, 282.6953125],
 [70.0, 70.0, 92.5, 92.5],
 [81.25, 81.25, 138.125, 138.125],
 [85.0, 85.0, 100.0, 100.0],
 [95.0, 95.0, 105.0, 105.0],
 [115.0, 115.0, 130.0, 130.0],
 [122.5, 122.5, 153.75, 153.75],
 [125.0, 125.0, 135.0, 135.0],
 [145.0, 145.0, 162.5, 162.5],
 [155.0, 155.0, 170.0, 170.0],
 [165.0, 165.0, 175.0, 175.0],
 [175.01953125, 175.01953125, 600.3125, 600.3125],
 [185.0, 185.0, 195.0, 195.0],
 [190.0, 190.0, 221.875, 221.875],
 [205.0, 205.0, 215.0, 215.0],
 [205.9375, 205.9375, 359.453125, 359.453125],
 [210.0, 210.0, 233.75, 233.75],
 [225.0, 225.0, 242.5, 242.5],
 [235.0, 235.0, 250.0, 250.0],
 [245.0, 245.0, 255.0, 255.0],
 [265.0, 265.0, 275.0, 275.0],
 [270.0, 270.0, 292.5, 292.5],
 [281.25, 281.25, 335.0, 335.0],
 [285.0, 285.0, 300.0, 300.0],
 

In [249]:
df=pd.DataFrame(mat)

In [250]:
mat.shape

(75, 25)

In [251]:
a={"a":[0,1,2,3]}
a

{'a': [0, 1, 2, 3]}

In [252]:
a.values()

dict_values([[0, 1, 2, 3]])

In [254]:
fig, ax=plt.subplots(figsize=[6,6,])
# collection = mc.CircleCollection(10*sizes,
#                                      #edgecolors=edge_colors, 
#                                      offsets=xy, 
#                                      transOffset=ax.transData, 
#                                      #facecolors=_colors,
#                                      linewidths=2)
collection = mc.RegularPolyCollection(
    numsides=4, 
    rotation=np.pi/4,sizes=100*sizes,
    facecolors=facecolors,
    #edgecolors=("black",),
    #linewidths=(1,),

    offset_transform=ax.transData,
    )
ax.add_collection(collection)
ax.margins(0.1)

/home/koh/.local/lib/python3.8/site-packages/matplotlib/collections.py:963: RuntimeWarning: invalid value encountered in sqrt
  scale = np.sqrt(self._sizes) * dpi / 72.0 * self._factor


In [255]:
a=None

In [256]:
int(type(a)==type(None) or 10>1)

1

In [257]:
a=np.array([0,33,4444522])

In [258]:
a.astype(str)

array(['0', '33', '4444522'], dtype='<U21')

In [259]:
xstart=0.1
ystart=0.1
recnumx=4
recnumy=10
recnumy2=3
w1=0.5
h1=0.75
r1=4
w2=w1/r1
r2=10
h2=h1/r2
s1=0.5
s2=0.25
s1x=s1*r1/recnumx
s2x=s2*r1/recnumx
s1y=s1*r2*recnumy2/recnumy
s2y=s2*r2*recnumy2/recnumy
print(s1x, s2x, s1y,s2y)
fig=plt.figure(figsize=[4,8])
ax=fig.add_axes([xstart,ystart,w1,h1])
rect = [Rectangle((0 - 0.5, 0 - 0.5), recnumx, recnumy)]
#         Rectangle((0 - s1/2, 0 - s1/2), s1, s1),
#        Rectangle((1 - s2/2, 0 - s2/2), s2, s2),
#         Rectangle((2 - s2/2, 0 - s2/2), s2, s2),
#         Rectangle((3 - s2/2, 0 - s2/2), s2, s2),
#        Rectangle((0 - s1/2, 1 - s1/2), s1, s1),
#        Rectangle((1 - s2/2, 1 - s2/2), s2, s2),
#        Rectangle((1 - s2/2, 2 - s2/2), s2, s2)]
for _i in range(recnumy):
    rect.extend([Rectangle((0 - s1/2, _i - s1/2), s1, s1),
       Rectangle((1 - s2/2, _i - s2/2), s2, s2),
        Rectangle((2 - s2/2, _i - s2/2), s2, s2),])

pc = PatchCollection(rect, facecolor="b", alpha=1,
                     edgecolor="w")
ax.add_collection(pc)
ax.margins(0)
ax.axis("off")
ax=fig.add_axes([0.65,0.1,w2,h2])
rect = [Rectangle((0 -0.5, 0 - 0.5),1,recnumy2)]
for _i in range(recnumy2):
    rect.extend([Rectangle((0 - s1x/2, _i - s1x/2), s1x, s1y)])
pc = PatchCollection(rect, facecolor="b", alpha=1,
                     edgecolor="w")
ax.add_collection(pc)
ax.margins(0)
ax.axis("off")

0.5 0.25 1.5 0.75


(-0.5, 0.5, -0.5, 3.25)

In [266]:
r=0.5
rs=[]
for i in range(5):
    rs.append([r*np.cos(np.pi/2+(2*i)*2*np.pi/5),r*np.sin(np.pi/2+(2*i)*2*np.pi/5)])


In [267]:
fig, ax=plt.subplots()
rect = [Polygon(rs)]
pc = PatchCollection(rect, alpha=1,
                     edgecolor=None)
ax.add_collection(pc)
plt.ylim(-0.5,0.5)
plt.xlim(-0.5,0.5)

(-0.5, 0.5)