In [86]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
import matplotlib.collections as mc
from matplotlib import transforms
import numpy as np
from sklearn.cluster import AgglomerativeClustering
import scipy.cluster.hierarchy as sch
import fastcluster as fcl
from scipy.spatial.distance import pdist, squareform
from matplotlib.collections import PatchCollection
from matplotlib.patches import Rectangle, Circle, RegularPolygon
import matplotlib as mpl
from decimal import Decimal
import seaborn as sns


In [87]:
%matplotlib tk

In [88]:
df=sns.load_dataset("penguins")

In [89]:
_df=df[["species","island", "sex"]]

In [90]:
_df.values

array([['Adelie', 'Torgersen', 'Male'],
       ['Adelie', 'Torgersen', 'Female'],
       ['Adelie', 'Torgersen', 'Female'],
       ...,
       ['Gentoo', 'Biscoe', 'Male'],
       ['Gentoo', 'Biscoe', 'Female'],
       ['Gentoo', 'Biscoe', 'Male']], dtype=object)

In [91]:
_df=_df.fillna("NA")

In [92]:
import numpy as np
from kmodes.kmodes import KModes

km = KModes(n_clusters=3, init='Huang', n_init=5, verbose=1)


clusters = km.fit_predict(_df.values)

In [156]:
val=df[["bill_length_mm","bill_depth_mm","flipper_length_mm"]].dropna(0)

<ipython-input-156-fa2fba455c93>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  val=df[["bill_length_mm","bill_depth_mm","flipper_length_mm"]].dropna(0)


In [180]:
X=val.values

In [181]:
X=(X-np.mean(X,axis=0)[None,:])/np.std(X,axis=0)[None,:]

In [182]:
from sklearn.cluster import KMeans

In [183]:
kmeans=KMeans(n_clusters=3, random_state=0, n_init="auto").fit(X)

In [184]:
X.mean(axis=0)

array([ 1.66208827e-16, -1.41277503e-15, -8.31044135e-16])

In [185]:
kmeans.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [186]:
dfX=pd.DataFrame(X, columns=["bill_length_mm","bill_depth_mm","flipper_length_mm"])

In [187]:
dfX["kmeans"]=kmeans.labels_
dfX["mean"]=X.mean(axis=1)

In [188]:
dfX=dfX.sort_values(['kmeans', 'mean'], ascending=[True, True])

In [189]:
dfX.index

Int64Index([207, 157, 212, 163, 165, 192, 189, 213, 203, 194,
            ...
            130,  84, 136,  52,  34,  94,  48, 100,  60,  16],
           dtype='int64', length=342)

In [193]:
srtindex=np.lexsort((X.mean(axis=1),kmeans.labels_))

In [194]:
srtindex

array([207, 157, 212, 163, 165, 192, 189, 213, 203, 194, 179, 154, 151,
       201, 161, 172, 186, 156, 169, 175, 215, 197, 187, 159, 200,  72,
       210,  42, 216, 170, 128, 199, 110, 195, 185, 168, 158, 218, 177,
       174, 153, 178, 193, 196, 152, 164, 209, 206,  18, 176, 184, 202,
       167, 166, 208, 162, 160, 155, 204, 191, 217, 198, 211, 180, 190,
       182, 188, 214, 235, 259, 227, 229, 257, 243, 327, 275, 255, 250,
       325, 277, 279, 267, 219, 261, 224, 303, 265, 251, 264, 271, 231,
       297, 317, 281, 269, 237, 225, 233, 305, 311, 245, 295, 337, 287,
       331, 313, 340, 307, 240, 285, 221, 247, 241, 323, 333, 338, 301,
       283, 273, 328, 223, 244, 232, 299, 292, 293, 335, 268, 276, 246,
       228, 258, 270, 274, 289, 280, 242, 316, 321, 309, 226, 239, 324,
       262, 319, 306, 290, 253, 249, 329, 238, 222, 315, 234, 236, 341,
       298, 291, 256, 230, 248, 288, 254, 272, 322, 278, 336, 339, 263,
       302, 312, 260, 300, 296, 266, 314, 326, 294, 330, 286, 31

In [151]:
# m=np.mean(X, axis=1)
# print(X.shape,m.shape)
# msort=np.argsort(m)

# X=X[msort]
# _labels=kmeans.labels_[msort]

# lsort=np.argsort(_labels)
# X=X[lsort]
# _labels=_labels[lsort]

In [196]:
arr_1 = np.array(["apple", "ball", "cat", "dog"])
arr_1.dtype

In [203]:
type(arr_1[0])==np.str_

In [209]:
a=[3,3,3,3,5,5,5,5,5,5,2,2,2]
u, i, c=np.unique(a, return_counts=True, return_index=True
         )
u[np.argsort(i)]

In [210]:
d={"a":0}
d.update({"b":1})

In [211]:
d

{'a': 0, 'b': 1}

In [204]:
X.mean(axis=1)

array([-0.50579872, -0.58239602, -0.218398  , -0.26624278,  0.04126657,
       -0.67016479, -0.01519041, -0.62806727,  0.13873929, -0.73705352,
       -0.84568382, -0.54571612,  0.12363023,  0.02832773, -0.71583734,
       -0.14718731,  0.42001039, -0.77266946,  0.69802881, -0.81908103,
       -0.61514033, -0.4270213 , -0.56729425, -0.80144379, -0.56189974,
       -0.38350707, -0.4129914 , -0.80973372, -0.41012837, -0.89064307,
       -0.79461676, -0.46729995, -0.29071165, -0.62590165,  0.2621114 ,
       -0.09073034, -0.37379982, -0.49609016, -0.32416197, -0.75936277,
       -0.12020937, -0.61045512,  0.32505994, -0.8435169 , -0.24466464,
       -0.3090582 , -0.61730065, -0.6169209 ,  0.34986367, -0.52556919,
       -0.24466794, -0.67806507,  0.25780795, -0.74604817, -0.14467364,
       -0.59606397, -0.11230118, -1.01976044, -0.22128153, -0.92300432,
        0.36677441, -0.78992626, -0.20689368, -0.87013489, -0.21012986,
       -0.8161645 , -0.14971549, -0.84278909,  0.18119546, -0.58

In [197]:
np.array([0.9, 'str', 1])

array(['0.9', 'str', '1'], dtype='<U32')

In [152]:
plt.subplots()
sns.heatmap(X)

<Axes: >

In [16]:
#sizes=np.array([mat[i,j] for i in range(mat.shape[0]) for j in range(mat.shape[1])])


In [17]:
mat=np.concatenate([0.5*np.random.uniform(0,1,size=[50, 25]),np.random.uniform(0,1,size=[25, 25])])

In [18]:
from scipy.stats import zscore

In [19]:
mat=zscore(mat, axis=0)

In [20]:
labels=["sample"+str(i) for i in range(75)]

In [21]:
xori=0.1
yori=0.1
ltreew=0.15
ltreeh=0.75
ttreew=0.6
ttreeh=0.1
hmapw=ttreew
hmaph=ltreeh
_tcmap=plt.get_cmap("tab20c")
tcmap = _tcmap(np.linspace(0, 1, 5))
sch.set_link_color_palette([mpl.colors.rgb2hex(rgb[:3]) for rgb in tcmap])
fig=plt.figure(figsize=[8*mat.shape[1]/mat.shape[0],8,])
ax0=fig.add_axes([xori,yori,ltreew,ltreeh])
D=squareform(pdist(mat,metric="euclidean"))
Y = sch.linkage(D, method="ward")

Z = sch.dendrogram(Y,ax=ax0,orientation="left",labels=labels,
                   above_threshold_color='black')
ax0.axis('off')

_tcmap=plt.get_cmap("tab20b")
tcmap = _tcmap(np.linspace(0, 1, 5))
sch.set_link_color_palette([mpl.colors.rgb2hex(rgb[:3]) for rgb in tcmap])
ax1=fig.add_axes([xori+ltreew,yori+ltreeh,ttreew,ttreeh])

Dt=squareform(pdist(mat.T,metric="euclidean"))
Yt = sch.linkage(Dt, method="ward")

Zt = sch.dendrogram(Yt,ax=ax1,orientation="top",above_threshold_color='black')
ax1.axis('off')

mat=mat[Z['leaves']]
mat=mat[:,Zt['leaves']]
row_col=[ [j,i] for i in range(mat.shape[0]) for j in range(mat.shape[1])]
sizes=mat.flatten()
cmap=plt.get_cmap("hot")
# facecolors=np.array([cmap(i) for i in mat.flatten()])
_mat=mat.flatten()
_mat=(_mat-np.min(_mat))/(np.max(_mat)-np.min(_mat))
facecolors=cmap(_mat)
rect = [Rectangle((x - 0.5, y - 0.5), 1, 1)
                  for x, y in row_col]
# circle=[Circle((x, y), 0.5) for x, y in row_col]
    # Create patch collection with specified colour/alpha
pc = PatchCollection(rect, facecolor=facecolors, alpha=1,
                     edgecolor=None)
ax=fig.add_axes([xori+ltreew,yori,hmapw,hmaph])
ax.add_collection(pc)
ax.margins(0.00)
_=ax.set_yticks(np.arange(mat.shape[0]))
_=ax.set_xticks(np.arange(mat.shape[1]))
ax.yaxis.tick_right()
axc=fig.add_axes([0.87,0.065,0.1,0.01])
norm = mpl.colors.Normalize(vmin=np.amin(mat), vmax=np.amax(mat))

cb1 = mpl.colorbar.ColorbarBase(axc, cmap=cmap,
                                norm=norm,
                                orientation='horizontal')
cb1.set_label('Some Units')

<ipython-input-21-e1ce0e46d333>:15: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  Y = sch.linkage(D, method="ward")
<ipython-input-21-e1ce0e46d333>:27: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  Yt = sch.linkage(Dt, method="ward")


In [25]:
aa, b,c=zip(*sorted(zip(Z["icoord"], Z["dcoord"], Z["color_list"])))

In [27]:
aa

([5.0, 5.0, 15.0, 15.0],
 [10.0, 10.0, 30.0, 30.0],
 [20.0, 20.0, 102.8125, 102.8125],
 [25.0, 25.0, 35.0, 35.0],
 [45.0, 45.0, 60.0, 60.0],
 [52.5, 52.5, 83.75, 83.75],
 [55.0, 55.0, 65.0, 65.0],
 [61.40625, 61.40625, 210.0, 210.0],
 [68.125, 68.125, 137.5, 137.5],
 [75.0, 75.0, 92.5, 92.5],
 [85.0, 85.0, 100.0, 100.0],
 [95.0, 95.0, 105.0, 105.0],
 [115.0, 115.0, 130.0, 130.0],
 [122.5, 122.5, 152.5, 152.5],
 [125.0, 125.0, 135.0, 135.0],
 [135.703125, 135.703125, 347.8125, 347.8125],
 [145.0, 145.0, 160.0, 160.0],
 [155.0, 155.0, 165.0, 165.0],
 [175.0, 175.0, 185.0, 185.0],
 [180.0, 180.0, 200.0, 200.0],
 [190.0, 190.0, 230.0, 230.0],
 [195.0, 195.0, 205.0, 205.0],
 [215.0, 215.0, 225.0, 225.0],
 [220.0, 220.0, 240.0, 240.0],
 [235.0, 235.0, 245.0, 245.0],
 [241.7578125, 241.7578125, 614.375, 614.375],
 [255.0, 255.0, 265.0, 265.0],
 [260.0, 260.0, 280.0, 280.0],
 [270.0, 270.0, 316.25, 316.25],
 [275.0, 275.0, 285.0, 285.0],
 [293.125, 293.125, 402.5, 402.5],
 [295.0, 295.0, 310.0

In [31]:
df=pd.DataFrame(mat)

In [32]:
mat.shape

(75, 25)

In [40]:
a={"a":[0,1,2,3]}
a

{'a': [0, 1, 2, 3]}

In [47]:
a.values()

dict_values([[0, 1, 2, 3]])

In [56]:
fig, ax=plt.subplots(figsize=[6,6,])
# collection = mc.CircleCollection(10*sizes,
#                                      #edgecolors=edge_colors, 
#                                      offsets=xy, 
#                                      transOffset=ax.transData, 
#                                      #facecolors=_colors,
#                                      linewidths=2)
collection = mc.RegularPolyCollection(
    numsides=4, 
    rotation=np.pi/4,sizes=100*sizes,
    facecolors=facecolors,
    #edgecolors=("black",),
    #linewidths=(1,),
    offsets=xy,
    offset_transform=ax.transData,
    )
ax.add_collection(collection)
ax.margins(0.1)

In [25]:
a=None

In [27]:
int(type(a)==type(None) or 10>1)

1

In [262]:
a=np.array([0,33,4444522])

In [263]:
a.astype(str)

array(['0', '33', '4444522'], dtype='<U21')

In [23]:
xstart=0.1
ystart=0.1
recnumx=4
recnumy=10
recnumy2=3
w1=0.5
h1=0.75
r1=4
w2=w1/r1
r2=10
h2=h1/r2
s1=0.5
s2=0.25
s1x=s1*r1/recnumx
s2x=s2*r1/recnumx
s1y=s1*r2*recnumy2/recnumy
s2y=s2*r2*recnumy2/recnumy
print(s1x, s2x, s1y,s2y)
fig=plt.figure(figsize=[4,8])
ax=fig.add_axes([xstart,ystart,w1,h1])
rect = [Rectangle((0 - 0.5, 0 - 0.5), recnumx, recnumy)]
#         Rectangle((0 - s1/2, 0 - s1/2), s1, s1),
#        Rectangle((1 - s2/2, 0 - s2/2), s2, s2),
#         Rectangle((2 - s2/2, 0 - s2/2), s2, s2),
#         Rectangle((3 - s2/2, 0 - s2/2), s2, s2),
#        Rectangle((0 - s1/2, 1 - s1/2), s1, s1),
#        Rectangle((1 - s2/2, 1 - s2/2), s2, s2),
#        Rectangle((1 - s2/2, 2 - s2/2), s2, s2)]
for _i in range(recnumy):
    rect.extend([Rectangle((0 - s1/2, _i - s1/2), s1, s1),
       Rectangle((1 - s2/2, _i - s2/2), s2, s2),
        Rectangle((2 - s2/2, _i - s2/2), s2, s2),])

pc = PatchCollection(rect, facecolor="b", alpha=1,
                     edgecolor="w")
ax.add_collection(pc)
ax.margins(0)
ax.axis("off")
ax=fig.add_axes([0.65,0.1,w2,h2])
rect = [Rectangle((0 -0.5, 0 - 0.5),1,recnumy2)]
for _i in range(recnumy2):
    rect.extend([Rectangle((0 - s1x/2, _i - s1x/2), s1x, s1y)])
pc = PatchCollection(rect, facecolor="b", alpha=1,
                     edgecolor="w")
ax.add_collection(pc)
ax.margins(0)
ax.axis("off")

0.5 0.25 1.5 0.75


(-0.5, 0.5, -0.5, 3.25)

In [34]:
fig, ax=plt.subplots()
rect = [RegularPolygon((0.5,0.5), 3, radius=0.5)]
pc = PatchCollection(rect, alpha=1,
                     edgecolor=None)
ax.add_collection(pc)